### PR TITLE
Fix/#32

### LINKED ISSUE #32: Bug in `set_indexing_prop!` following `add_vertex!`
MWE:
```
julia> mg = MetaGraph(DiGraph())
{0, 0} undirected Int64 metagraph with Float64 weights defined by :weight (default weight 1.0)

julia> add_vertex!(mg)
true

julia> set_indexing_prop!(mg, 1, :a, 10)
Set(Symbol[:a])

julia> props(mg, 1)
Dict{Symbol,Any} with 1 entry:
  :a => 10

julia> mg.metaindex
Dict{Symbol,Dict{Any,Integer}} with 1 entry:
  :a => Dict{Any,Integer}(Pair{Any,Integer}(10, 1))

julia> add_vertex!(mg)
true

julia> set_indexing_prop!(mg, 2, :a, 20)
ERROR: KeyError: key 2 not found
Stacktrace:
 [1] getindex at ./dict.jl:474 [inlined]
 [2] set_indexing_prop!(::MetaGraphs.MetaGraph{Int64,Float64}, ::Int64, ::Symbol, ::Int64) at /Users/seth/.julia/v0.6/MetaGraphs/src/MetaGraphs.jl:361
```

It seems that the `delete!` call on L361 is the problem.

@kescobo - do you have a few minutes to chase this down?

### PR DESCRIPTION
**Pull request by skleinbo**
This ought to fix https://github.com/JuliaGraphs/MetaGraphs.jl/issues/32

It passes the same tests on Julia 0.7 as before. Unit test for the specific issue added and passes. 

Now you can issue
`set_indexing_prop!(g, vert, :prop, val)` even if `vert` doesn't already have property `prop`.

### CODE REVIEW

**Review by sbromberger — APPROVED** [review]
Thank you, @skleinbo :)

File: src/MetaGraphs.jl [hunk 1]
```diff
@@ -360,7 +360,12 @@ function set_indexing_prop!(g::AbstractMetaGraph, v::Integer, prop::Symbol, val:
     (haskey(g.metaindex[prop], val) && g.vprops[v][prop] == val) && return g.indices
     haskey(g.metaindex[prop], val) && error("':$prop' index already contains $val")
 
-    delete!(g.metaindex[prop], g.vprops[v][prop])
+    if !haskey(g.vprops, v)
+        push!(g.vprops, v=>Dict{Symbol,Any}())
+    end
+    if haskey(g.vprops[v], :prop)
```
Comment (skleinbo) [inline src/MetaGraphs.jl:366]: Must read `prop` not `:prop`!
